# Generated by Django 5.2.17 on 2026-09-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('submitted_location', models.CharField(blank=True, max_length=255)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at', 'national_id'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('registered_location', models.CharField(blank=True, max_length=255)),
                ('exam_date', models.DateField(blank=True, db_index=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('cell', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['district', 'full_name'],
                'indexes': [models.Index(fields=['district', 'national_id'], name='monitoring__distric_49ea2f_idx')],
            },
        ),
    ]
