# Generated by Django 5.2.17 on 2026-09-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
