# Generated by Django 5.2.17 on 2026-09-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_submission_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
